version = 0.1
[default.deploy.parameters]
stack_name = "priceline-bedrock-lambda"
resolve_s3 = true
s3_prefix = "priceline-bedrock-lambda"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
